// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OVHAPI.Services;

namespace OVHAPI.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20210822153926_initial-creation")]
    partial class initialcreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("OVHAPI.Database.IPSchema", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geolocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnderAttack")
                        .HasColumnType("INTEGER");

                    b.HasKey("IP");

                    b.ToTable("IPs");
                });

            modelBuilder.Entity("OVHAPI.Database.LogsSchema+AttackLogs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAttacked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("OVHAPI.Database.LogsSchema+ErrorLogs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Application")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErrorTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("OVHAPI.Database.Settings", b =>
                {
                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumerKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordWebHookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPoint")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileName");

                    b.ToTable("Setttings");
                });
#pragma warning restore 612, 618
        }
    }
}
